### ISSUE TITLE
Selected vs total samples is wrong in memaxes

### ISSUE THREAD

**Issue by tgamblin** [scalability-llnl/MemAxes#1]
Not sure why but it doesn't look like `inspect` in the console does the right thing.  These are from the same run:

```
12:14:57$ $ inspect
12:14:57$ Selected Samples : 
12:14:57$ 88736
12:14:57$ Total Samples : 
12:14:57$ 10613

12:32:23$ $ inspect
12:32:23$ Selected Samples : 
12:32:23$ 120575
12:32:23$ Total Samples : 
12:32:23$ 10613
```

**Comment by alfredo-gimenez** [comment]
Fixed. I had moved from using indices to using std::sets to record selections, didn't update the inspect function, thanks!
